# Generated by Django 4.2.7 on 2023-12-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0002_remove_comment_level_remove_comment_lft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_image',
            new_name='comment',
        ),
    ]
