# Generated by Django 4.2.7 on 2023-12-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0003_rename_comment_image_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=13, max_length=500),
            preserve_default=False,
        ),
    ]
