# Generated by Django 4.2.7 on 2023-12-08 05:36

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0004_remove_comment_comment_remove_comment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ImageField(blank=True, null=True, upload_to='comment_image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pinapp.comment'),
        ),
    ]
