# Generated by Django 4.2.7 on 2023-12-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0006_comments_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
