# Generated by Django 4.2.7 on 2023-12-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0011_remove_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
